### ISSUE TITLE
Auga Compatibility 

### ISSUE THREAD

**Issue by SongS0ng** [blaxxun-boop/Resurrection#5]
Is it possible to make this compatible with auga, what happens is with this and auga it opens a menu that says something like "Menu" and gives yes and no. If you click no nothing happens but if you click yes the game closes to desktop. I asked in auga discord to see and they said

 "It's less about Auga being compatible as it is the other mod making compatibility for Auga. We have an API DLL that can be used for that"
 
 Mod: https://valheim.thunderstore.io/package/RandyKnapp/Auga/

**Comment by blaxxun-boop** [comment]
No, it's not, sorry. Auga is a terrible mod, it doesn't work with any other mod that ever so slightly touches the UI, since it straight up deletes vanilla UI elements. And yes, they say that they have an API, but there is no documentation for that whatsoever. Adding compatibility with Auga basically means rewriting your entire mod and keeping two different versions from that point on, one that works with Auga and one that works without Auga. Even the author of Auga struggled with adding Auga support to his mods and that says a lot.

But you can simply replace Auga with Minimal UI. It works out of the box with other mods and it has an Auga theme, which you can enabled and that makes it look like Auga.
https://valheim.thunderstore.io/package/Azumatt/Minimal_UI/
